### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by adships** [free/jiralert#19]
Is there a way to use Jira user/OATH token instead of user/pwd in the config/jiralert.yml?

**Comment by free** [comment]
Not currently, no. And I don't have plans to add it myself anytime soon.

That being said, if someone is interested in contributing, here's some relevant information:

- the Jira OAuth documentation is [here](https://developer.atlassian.com/server/jira/platform/oauth/);
- but you likely don't need to go all that deep into it, because JIRAlert uses the [go-jira client library](https://github.com/andygrunwald/go-jira) to communicate with Jira;
- and the go-jira documentation links to [a piece of code](https://gist.github.com/Lupus/edafe9a7c5c6b13407293d795442fe67) that shows how to create an OAuth authenticated go-jira client.

**Comment by adships** [comment]
Thanks, will try that out.

**Comment by dnicholson-fastly** [comment]
@adships did you ever get that working?

**Comment by adships** [comment]
No, I was pulled into other projects and I never got a chance to.
