### ISSUE TITLE
Support JSON formatted logs

### ISSUE THREAD

**Issue by tdabasinskas** [free/jiralert#30]
Hello,

Currently Jiralert relies on [glog](https://github.com/google/glog) library for logging. It seems that this library does not support output JSON-formatted logs, which makes it quite difficult to automatically capture and parse the logs in cloud environments.

In addition, it seems [there's](https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/67) [quite](https://github.com/danderson/metallb/issues/189) [a few](https://github.com/coredns/coredns/issues/1597) [complains](https://twitter.com/peterbourgon/status/972177627996831744) about the over about `glog` library, the way it's designed and configured.

Is there any strict dependency on `glog` or is it possible to replace it with something else (e.g. [logrus](https://github.com/Sirupsen/logrus)) that is more versatile and intuitive?

I can help with a PR if needed.

**Comment by free** [comment]
I personally don't have a preference for loggers. I used [`glog`](https://github.com/golang/glog) because I used to work at Google and was familiar with the concept. E.g. while one could argue that the use of the `flag` package breaks encapsulation or whatever, I for one prefer the flexibility of flags to configure where the logs go, what is being logged and from which module. And some implementations of flags (not sure about `glog` and `flag` in particular) allow you to change flag values at run time, essentially enabling and disabling verbose logging from one module or another.

That being said, feel free to put together a PR and I'll be happy to look at it. (When I can find the time.) (o:
