### ISSUE TITLE
Dockerize ssl certificate error problem

### ISSUE THREAD

**Issue by espekkaya** [free/jiralert#45]
Hello,

I want to dockerize jiralert project. I have done it but when I sent to alert to my jira, error accured.

```
{"Error":true,"Status":500,"Message":"JIRA request Issue.Search failed: No response returned: Get 'https://jira.example.com' x509: certificate signed by unknown authority"}
```

By the way your dockerize file unfortunetly throws error.

How and Where could I add "InsecureSkipVerify" in your code?

Here is my dockerfile:

```
FROM golang:1.8

WORKDIR /go/src/app

RUN go get github.com/free/jiralert/cmd/jiralert

COPY cert/-.csb.gov.tr.crt etc/ssl/certs/-.csb.gov.tr.crt

COPY config/jiralert.yml /go/src/app/config/jiralert.yml
COPY config/jiralert.tmpl /go/src/app/config/jiralert.tmpl

ENTRYPOINT ["jiralert"]
```

Thank you.

**Comment by free** [comment]
I'm not clear on who produces that error message, but if it's JIRAlert, it appears to say that the server at `https://jira.example.com` responded with an HTTP 500 due a self-signed certificate. I.e. it's the JIRA instance that doesn't like the certificate (and prevents JIRAlert from authenticating). As long as that's the case, there's no code change you can make in JIRAlert for the authentication to succeed.

**Comment by espekkaya** [comment]
Hello @free ,

Thank you for your response. When I standed up the service, it worked great without authanticate problem. 

I have searched that problem. Almost answer is the same. 

By the way I do not understand go language very well.

Here is a [answer](https://github.com/andygrunwald/go-jira/issues/52)

**Comment by free** [comment]
Right, so this appears to be the HTTP client in JIRAlert refusing to connect to your JIRA instance due to it using a self-signed certificate. The piece of code you are looking for is at [`pkg/notify/notify.go:30`](https://github.com/free/jiralert/blob/7a1b0b33f457efc9b7f8b4d36bb031b7fe0f68dc/pkg/notify/notify.go#L30). According to [go-jira code](https://github.com/andygrunwald/go-jira/blob/a8bdfed27ff42a9bb0468b8cf192871780919def/jira.go#L336), setting a custom `http.Transport` will cause that to be used instead of the default one (that refuses your certificate). Meaning you can use a `Transport` set up with `InsecureSkipVerify : true` there.

Better yet, you can add the self-signed certificate to the list of trusted certificates, either within JIRAlert (see [this example](https://golang.org/pkg/crypto/tls/#example_Dial)), or for your whole client machine: https://www.google.com/search?q=add+self+signed+certificate+to+trusted . Then you wouldn't completely circumvent all of the security provided by SSL/TLS.

**Comment by espekkaya** [comment]
Hello @free ,

I'm grateful for your help. I have figured it out problem via your writting.

import library :

```
	"net/http"
	"crypto/tls"
```

Just changed code notify.go:30

```
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify : true},
	}
	
	tp := jira.BasicAuthTransport{
		Username: c.User,
		Password: string(c.Password),
		Transport: tr,
	}
```

Have a good day.
